<solution>
<>
<trains>[102;93;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[102;93;42;33;96]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;F;T;T;T;T]
</>
<>
<trains>[102;93;41;33;95]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;F;T;T;T;T]
</>
<>
<trains>[102;93;55;33;95]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;F;T;T;T;T]
</>
<>
<trains>[102;93;54;33;95]
<signals>[F;F;F;F;T;T;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;F;T;T;T;T]
</>
<>
<trains>[102;93;54;33;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[101;93;54;34;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[100;93;54;35;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[99;93;54;36;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[98;93;54;37;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[97;93;54;38;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[96;93;54;39;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[96;93;54;40;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[96;93;54;41;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[96;93;54;42;95]
<signals>[T;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[96;93;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;94;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;80;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;81;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;67;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;68;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;69;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;70;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;101;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;102;54;42;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;T;T;F;F;F;F;F]
<rails>[T;T;F;T;F;F]
</>
<>
<trains>[96;102;54;42;95]
<signals>[F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<>
<trains>[96;102;68;42;94]
<signals>[F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<>
<trains>[96;102;67;42;93]
<signals>[F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<>
<trains>[96;102;66;42;93]
<signals>[F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<>
<trains>[96;102;65;42;93]
<signals>[F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<>
<trains>[96;102;34;42;93]
<signals>[F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<>
<trains>[96;102;33;42;93]
<signals>[F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<states> 32
<generated> 32
<time> 110.7844
</solution>
