<solution>
<>
<trains>[24;23;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[24;23;30;31]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[25;23;29;31]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[T;T]
</>
<>
<trains>[25;24;29;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[15;24;28;30]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;T]
</>
<>
<trains>[15;25;28;29]
<signals>[F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[16;25;27;29]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[16;15;27;28]
<signals>[F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[17;15;26;28]
<signals>[F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[17;16;26;27]
<signals>[F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[29;16;25;27]
<signals>[F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[29;17;25;26]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[30;17;24;26]
<signals>[F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[30;29;24;25]
<signals>[F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[T;F]
</>
<>
<trains>[31;29;23;25]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[31;30;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<states> 16
<generated> 59
<time> 119.514
</solution>
