<solution>
<>
<trains>[43;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[]
</>
<>
<trains>[43;42;41]
<signals>[F;F;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[44;42;41]
<signals>[F;F;F;T;T;T;T;T;T;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[45;42;41]
<signals>[F;F;F;F;T;T;T;T;T;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[46;42;41]
<signals>[F;F;F;F;F;T;T;T;T;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[47;42;41]
<signals>[F;F;F;F;F;F;T;T;T;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[48;42;41]
<signals>[F;F;F;F;F;F;F;T;T;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[49;42;41]
<signals>[F;F;F;F;F;F;F;F;T;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[50;42;41]
<signals>[F;F;F;F;F;F;F;F;F;T;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[51;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;T;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[52;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[53;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;T;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[54;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;T;T;F]
<rails>[]
</>
<>
<trains>[55;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;T;F]
<rails>[]
</>
<>
<trains>[56;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;F]
<rails>[]
</>
<>
<trains>[57;42;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[]
</>
<>
<trains>[58;42;41]
<signals>[F;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;43;41]
<signals>[F;F;T;T;T;T;T;T;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;44;41]
<signals>[F;F;F;T;T;T;T;T;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;45;41]
<signals>[F;F;F;F;T;T;T;T;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;46;41]
<signals>[F;F;F;F;F;T;T;T;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;47;41]
<signals>[F;F;F;F;F;F;T;T;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;48;41]
<signals>[F;F;F;F;F;F;F;T;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;49;41]
<signals>[F;F;F;F;F;F;F;F;T;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;50;41]
<signals>[F;F;F;F;F;F;F;F;F;T;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;51;41]
<signals>[F;F;F;F;F;F;F;F;F;F;T;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;52;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;53;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;T;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;54;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;55;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;F;F]
<rails>[]
</>
<>
<trains>[58;56;41]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[]
</>
<>
<trains>[58;57;41]
<signals>[T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;42]
<signals>[F;T;T;T;T;T;T;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;43]
<signals>[F;F;T;T;T;T;T;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;44]
<signals>[F;F;F;T;T;T;T;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;45]
<signals>[F;F;F;F;T;T;T;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;46]
<signals>[F;F;F;F;F;T;T;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;47]
<signals>[F;F;F;F;F;F;T;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;48]
<signals>[F;F;F;F;F;F;F;T;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;49]
<signals>[F;F;F;F;F;F;F;F;T;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;50]
<signals>[F;F;F;F;F;F;F;F;F;T;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;51]
<signals>[F;F;F;F;F;F;F;F;F;F;T;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;52]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;53]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;T;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;54]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;55]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[]
</>
<>
<trains>[58;57;56]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[]
</>
<states> 47
<generated> 49
<time> 1.8229
</solution>
