<solution>
<>
<trains>[102;93;42;33;96]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[102;93;42;33;96]
<signals>[T;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;T;F;F;T]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[101;94;41;34;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;F;T]
</>
<>
<trains>[101;94;41;34;95]
<signals>[F;T;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;T;F]
<rails>[F;T;T;T;F;T]
</>
<>
<trains>[100;80;40;65;95]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T;T;T;T;T]
</>
<>
<trains>[99;81;39;66;94]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;T;T]
</>
<>
<trains>[98;81;38;66;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[T;T;F;T;T;T]
</>
<>
<trains>[97;67;37;66;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;F;T;T;T]
</>
<>
<trains>[96;68;36;66;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T]
</>
<>
<trains>[96;68;35;66;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;T;T;T;T]
</>
<>
<trains>[96;69;35;66;93]
<signals>[F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;F;T]
</>
<>
<trains>[96;70;34;67;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;F;T]
</>
<>
<trains>[96;70;33;68;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[F;T;T;T;T;F]
</>
<>
<trains>[96;101;33;68;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;T;F;T;F]
</>
<>
<trains>[96;102;33;54;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;T;F;T;T]
</>
<>
<trains>[96;102;33;55;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;T;F;T;T]
</>
<>
<trains>[96;102;33;55;93]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[96;102;33;41;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;T;T]
</>
<>
<trains>[96;102;33;42;93]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F;T;F;T;T]
</>
<states> 19
<generated> 60
<time> 119.4092
</solution>
