<solution>
<>
<trains>[28;27;36;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;27;36;37]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[29;27;36;37]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[30;27;36;37]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[30;27;36;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[30;27;35;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[30;27;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[30;27;34;37]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[30;28;34;37]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[30;28;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[31;28;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[31;28;34;37]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[31;29;34;37]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[31;30;34;37]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[31;30;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[32;30;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[32;30;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[32;31;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[32;31;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[33;31;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[33;31;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[33;32;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[33;32;34;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[33;32;20;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[33;32;20;37]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[33;32;19;37]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[33;32;19;37]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[33;32;18;37]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[33;32;18;37]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;30;37]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;29;37]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;29;37]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;28;37]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;28;37]
<signals>[F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;37]
<signals>[F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;36]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;36]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;35]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;34]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;34]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;20]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[33;32;27;20]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[34;32;27;20]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;20]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;20]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;19]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;19]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;18]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;18]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;30]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;29]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;29]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;32;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;33;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[35;33;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[36;33;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[36;33;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[36;34;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[36;35;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[36;35;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[37;35;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[37;35;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[37;36;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<states> 65
<generated> 1280
<time> 184.4233
</solution>
