<solution>
<>
<trains>[28;27;36;37]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;27;36;37]
<signals>[F;T;F;T;F;F;F;F;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[29;27;36;37]
<signals>[F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[30;27;36;37]
<signals>[F;T;F;T;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[18;27;36;37]
<signals>[F;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[19;27;36;37]
<signals>[F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[20;27;36;37]
<signals>[F;T;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[20;28;36;37]
<signals>[F;T;F;F;F;F;F;F;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[20;29;36;37]
<signals>[F;T;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[20;30;36;37]
<signals>[F;T;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[20;18;36;37]
<signals>[F;T;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;T;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;35;37]
<signals>[F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;T;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;34;37]
<signals>[F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;T;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;33;37]
<signals>[F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;32;37]
<signals>[F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;31;37]
<signals>[F;F;F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;30;37]
<signals>[F;F;F;F;F;F;F;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;29;37]
<signals>[F;F;F;F;F;F;F;F;T;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;28;37]
<signals>[F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;27;37]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;T;F;T;F]
<rails>[T;T]
</>
<>
<trains>[20;19;27;36]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;27;35]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;27;34]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;F;T;F;T;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[20;19;27;33]
<signals>[F;F;F;F;F;T;F;F;F;F;T;F;T;F;T;F;T;F;F;T;F;T;F;F]
<rails>[T;F]
</>
<>
<trains>[34;19;27;32]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;T;F;T;F;F;F;F;T;F;T;F;F]
<rails>[T;F]
</>
<>
<trains>[35;19;27;31]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;T;F;F;F;F;F;F;T;F;T;F;F]
<rails>[T;F]
</>
<>
<trains>[36;19;27;30]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[T;F]
</>
<>
<trains>[37;19;27;29]
<signals>[F;F;F;T;F;T;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[37;20;27;29]
<signals>[F;F;F;F;F;T;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[37;34;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[37;35;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[37;36;27;28]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<states> 32
<generated> 43
<time> 5.4176
</solution>
