<solution>
<>
<trains>[24;23;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[24;23;30;31]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[25;23;30;31]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[25;23;30;31]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[25;24;30;31]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[25;24;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;24;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;24;30;31]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;25;30;31]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[26;25;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[27;25;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[27;25;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[27;26;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[27;26;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;26;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;26;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;27;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;27;30;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;27;29;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[T;T]
</>
<>
<trains>[28;27;29;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[28;27;17;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[28;27;17;31]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[28;27;16;31]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[28;27;16;31]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[28;27;15;31]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F]
</>
<>
<trains>[28;27;15;31]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;25;31]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;25;31]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;24;31]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;24;31]
<signals>[F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;31]
<signals>[F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;31]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;30]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;29]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;29]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;17]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;17]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;16]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;16]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;15]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;15]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;25]
<signals>[T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;25]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;F]
</>
<>
<trains>[28;27;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[29;27;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[29;27;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[29;28;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[29;28;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[30;28;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[30;28;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[30;29;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[30;29;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[31;29;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[F;T]
</>
<>
<trains>[31;29;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<>
<trains>[31;30;23;24]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[F;T]
</>
<states> 57
<generated> 939
<time> 74.1965
</solution>
