<solution>
<>
<trains>[21;38;61;78;101;118;141;158;181]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[21;38;61;78;101;118;141;158;181]
<signals>[F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[22;37;62;77;102;117;142;157;182]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[22;37;62;77;102;117;142;157;182]
<signals>[F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;F;T;F;T;F;T]
</>
<>
<trains>[23;56;63;96;103;136;143;176;183]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;F;T;F;T;F;T]
</>
<>
<trains>[23;56;63;96;103;136;143;176;183]
<signals>[F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;F;T;F;T;F;T]
</>
<>
<trains>[24;55;64;95;104;135;144;175;184]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[24;55;64;95;104;135;144;175;184]
<signals>[F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[25;54;65;94;105;134;145;174;185]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[25;54;65;94;105;134;145;174;185]
<signals>[F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[26;53;66;93;106;133;146;173;186]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[26;53;66;93;106;133;146;173;186]
<signals>[F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[27;52;67;92;107;132;147;172;187]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[27;52;67;92;107;132;147;172;187]
<signals>[F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[28;51;68;91;108;131;148;171;188]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[28;51;68;91;108;131;148;171;188]
<signals>[F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[29;50;69;90;109;130;149;170;189]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[29;50;69;90;109;130;149;170;189]
<signals>[F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[30;49;70;89;110;129;150;169;190]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[30;49;70;89;110;129;150;169;190]
<signals>[F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[31;48;71;88;111;128;151;168;191]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[31;48;71;88;111;128;151;168;191]
<signals>[F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[32;47;72;87;112;127;152;167;192]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[32;47;72;87;112;127;152;167;192]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[33;46;73;86;113;126;153;166;193]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[33;46;73;86;113;126;153;166;193]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[34;45;74;85;114;125;154;165;194]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[34;45;74;85;114;125;154;165;194]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[35;44;75;84;115;124;155;164;195]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[35;44;75;84;115;124;155;164;195]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F]
<rails>[T;T;T;T;T;T;T;T]
</>
<>
<trains>[36;43;76;83;116;123;156;163;196]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[F;T;F;T;F;T;F;T]
</>
<>
<trains>[36;43;76;83;116;123;156;163;196]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F]
<rails>[T;F;T;F;T;F;T;F]
</>
<>
<trains>[37;62;77;102;117;142;157;182;197]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;F;T;F;T;F;T;F]
</>
<>
<trains>[37;62;77;102;117;142;157;182;197]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;T;F;F]
<rails>[T;F;T;F;T;F;T;F]
</>
<>
<trains>[38;61;78;101;118;141;158;181;198]
<signals>[F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F;F]
<rails>[T;T;T;F;T;T;T;T]
</>
<states> 35
<generated> 315
<time> 649.1511
</solution>
